source 'https://rubygems.org'

gem 'rails', '3.2.14'

# Bundle edge Rails instead:
# gem 'rails', :git => 'git://github.com/rails/rails.git'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'

  # See https://github.com/sstephenson/execjs#readme for more supported runtimes
  # gem 'therubyracer', :platforms => :ruby

  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'

gem 'haml-rails'

gem 'tire' # talk to elasticsearch from ruby

gem 'mongo_mapper', "0.13.0.beta1"
gem 'bson_ext' # makes mongomapper go faster

gem 'geocoder' # takes postcode/street address to longitude and lagitude
# gem 'gmaps4rails'

gem 'devise'
gem 'mm-devise' # devise for mongo

group :development, :test do
  gem 'tire-contrib', require: 'tire/rails/logger'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'pry-rails'
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'meta_request'
end
